version: '3.9'

services:
  api:
    build: ./api
    container_name: single-sign-omni-api
    ports:
      - '8080:8080'
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        # VITE_API_URL: http://springboot-api:8080
        VITE_API_URL: http://localhost:8080
    container_name: single-sign-omni-frontend
    ports:
      - '5173:80'
    networks:
      - app-network
    depends_on:
      - api

networks:
  app-network:
